/**
 * Created by meng_jin on 2018/9/14.
 */
$(function(){
    FastClick.attach(document.body);
    $('.receive_btn').click(function(e){
        e.stopPropagation();
        $('.common_box').fadeIn();
    });
    $(document).on('click','.common_model',function(e){
        e.stopPropagation()
    });
    $('.sign_btn').click(function(e){
        e.stopPropagation();
        $('.sign_box').fadeIn();
    });
    $(document).on('click','.sign_model',function(e){
        e.stopPropagation()
    });
    $(document).on('click',function(){
        $('.model_box').fadeOut();
    });
    $(".sign_box_cancel").on('click',function(e){
        e.stopPropagation();
        $('.sign_box').fadeOut();
    });
});